# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'
    - name: Test
      run: go test -v ./...
  coverage:
    name: Check test coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    
    - name: generate test coverage
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml
        ## Test Coverage Badge
        profile: cover.out
        #threshold-total: 95

        ## when token is not specified (value '') this feature is turned off
        ## in this example badge is created and committed only for main branch
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        ## name of branch where badges are stored
        ## ideally this should be orphan branch (see below how to create this branch)
        git-branch: badges 
    - name: visualize coverage
      run: go tool cover -html=cover.out -o=cover.html
    - name: upload visualization
      uses: actions/upload-artifact@v4
      with:
        name: coverage-visualization
        path: ./cover.html